- name: Iniciando aprovisionamento
  hosts: "{{ hostname }}"
  tasks:
    - name: Add Docker User
      user:
        name: docker
        comment: Docker user
        uid: 1040
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
    - name: Yum install git
      yum:
        name: git
        state: latest
    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
      become: yes
    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
      become: yes
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes
    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1
    - name: Download repository 
      git:
        repo: https://github.com/renatogalera/iaclinuxfiap2019.git
        dest: /tmp/ansible
    - name: Setup docker-compose.yml
      command: docker-compose -f /tmp/ansible/docker-compose.yml up -d
